<a href="https://colab.research.google.com/github/vrunstar/pandas/blob/main/Notebooks/cafe_sales.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np
import seaborn as sns
from matplotlib import pyplot as plt

In [ ]:
df = pd.read_csv('/content/sample_data/dirty_cafe_sales.csv')

In [ ]:
df.sample(5)

,Transaction ID,Item,Quantity,Price Per Unit,Total Spent,Payment Method,Location,Transaction Date
184,TXN_3831848,UNKNOWN,1,4.0,4.0,Digital Wallet,Takeaway,2023-11-03
2142,TXN_8777692,Coffee,4,2.0,8.0,Credit Card,In-store,2023-12-06
1469,TXN_4773465,Coffee,5,2.0,ERROR,Digital Wallet,Takeaway,2023-11-28
9035,TXN_9938977,Cake,5,3.0,15.0,Cash,In-store,2023-12-18
1957,TXN_2623927,Sandwich,2,4.0,8.0,UNKNOWN,NaN,2023-01-27

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 8 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Transaction ID    10000 non-null  object
 1   Item              9667 non-null   object
 2   Quantity          9862 non-null   object
 3   Price Per Unit    9821 non-null   object
 4   Total Spent       9827 non-null   object
 5   Payment Method    7421 non-null   object
 6   Location          6735 non-null   object
 7   Transaction Date  9841 non-null   object
dtypes: object(8)
memory usage: 625.1+ KB

In [ ]:
df.describe()

       Transaction ID   Item Quantity Price Per Unit Total Spent  \
count           10000   9667     9862           9821        9827
unique          10000     10        7              8          19
top       TXN_9226047  Juice        5            3.0         6.0
freq                1   1171     2013           2429         979

        Payment Method  Location Transaction Date
count             7421      6735             9841
unique               5         4              367
top     Digital Wallet  Takeaway          UNKNOWN
freq              2291      3022              159

In [ ]:
df.isnull().sum()

Transaction ID         0
Item                 333
Quantity             138
Price Per Unit       179
Total Spent          173
Payment Method      2579
Location            3265
Transaction Date     159
dtype: int64

In [ ]:
df.duplicated().sum()

0

In [ ]:
df.dtypes
df.nunique()

Transaction ID      10000
Item                   10
Quantity                7
Price Per Unit          8
Total Spent            19
Payment Method          5
Location                4
Transaction Date      367
dtype: int64

In [ ]:
df.info()
df.isna().sum()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 8 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Transaction ID    10000 non-null  object
 1   Item              9667 non-null   object
 2   Quantity          9862 non-null   object
 3   Price Per Unit    9821 non-null   object
 4   Total Spent       9827 non-null   object
 5   Payment Method    7421 non-null   object
 6   Location          6735 non-null   object
 7   Transaction Date  9841 non-null   object
dtypes: object(8)
memory usage: 625.1+ KB

Transaction ID         0
Item                 333
Quantity             138
Price Per Unit       179
Total Spent          173
Payment Method      2579
Location            3265
Transaction Date     159
dtype: int64

In [ ]:
df.fillna({'Item':"unknown"}, inplace = True)
df.fillna({'Location':"unknown"}, inplace = True)
df.fillna({'Payment Method':"unknown"}, inplace = True)
df.fillna({'Quantity':0}, inplace = True)
df.fillna({'Price Per Unit':0}, inplace = True)
df.fillna({'Total Spent':0}, inplace = True)
df.isnull().sum()

Transaction ID      0
Item                0
Quantity            0
Price Per Unit      0
Total Spent         0
Payment Method      0
Location            0
Transaction Date    0
dtype: int64

In [ ]:
df['Transaction Date'].isin(['UNKNOWN']).value_counts()

df['Transaction Date'] = df['Transaction Date'].replace(['UNKNOWN', 'ERROR'], '1900-01-01')
df['Transaction Date'].isin(['UNKNOWN']).value_counts()

df['Transaction Date'] = pd.to_datetime(df['Transaction Date'])

df.fillna({'Transaction Date': '1900-01-01'}, inplace= True)
print(df.isnull().sum())

print(df.sample(10))

Transaction ID      0
Item                0
Quantity            0
Price Per Unit      0
Total Spent         0
Payment Method      0
Location            0
Transaction Date    0
dtype: int64
     Transaction ID      Item Quantity Price Per Unit Total Spent  \
9558    TXN_9756401     Salad        3            5.0        15.0
4       TXN_3160411    Coffee        2            2.0         4.0
5860    TXN_7030681     Juice        1            3.0         3.0
7481    TXN_9455977       Tea        1            1.5         1.5
1141    TXN_6908287    Cookie        1            1.0         1.0
3257    TXN_2955691      Cake        1            3.0         3.0
9753    TXN_3507013     Juice        1          ERROR         3.0
1627    TXN_5396450     Juice        3            3.0         9.0
4767    TXN_8725721  Sandwich        1            4.0         4.0
40      TXN_2083138  Smoothie        3            4.0        12.0

      Payment Method  Location Transaction Date
9558            Cash  In-store       2023-02-04
4     Digital Wallet  In-store       2023-06-11
5860            Cash   unknown       2023-10-01
7481  Digital Wallet  Takeaway       2023-03-10
1141            Cash  In-store       2023-08-04
3257         unknown  Takeaway       2023-04-04
9753  Digital Wallet  In-store       2023-01-16
1627  Digital Wallet   unknown       2023-12-09
4767            Cash     ERROR       2023-06-04
40           unknown  In-store       2023-04-17

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 8 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Transaction ID    10000 non-null  object
 1   Item              10000 non-null  object
 2   Quantity          10000 non-null  object
 3   Price Per Unit    10000 non-null  object
 4   Total Spent       10000 non-null  object
 5   Payment Method    10000 non-null  object
 6   Location          10000 non-null  object
 7   Transaction Date  10000 non-null  datetime64[ns]
dtypes: datetime64[ns](1), object(7)
memory usage: 625.1+ KB

In [ ]:


print(f"{df['Item'].isin(['UNKNOWN', 'ERROR']).value_counts()}\n")
df['Item'] = df['Item'].replace(['UNKNOWN', 'ERROR'], 'unknown')
print(f"{df['Item'].isin(['UNKNOWN', 'ERROR']).value_counts()}\n")

print(f"{df['Location'].isin(['UNKNOWN', 'ERROR']).value_counts()}\n")
df['Location'] = df['Location'].replace(['UNKNOWN', 'ERROR'], 'unknown')
print(f"{df['Location'].isin(['UNKNOWN', 'ERROR']).value_counts()}\n")

print(f"{df['Payment Method'].isin(['UNKNOWN', 'ERROR']).value_counts()}\n")
df['Payment Method'] = df['Payment Method'].replace(['UNKNOWN', 'ERROR'], 'unknown')
print(f"{df['Payment Method'].isin(['UNKNOWN', 'ERROR']).value_counts()}\n")

print(f"{df['Quantity'].isin(['UNKNOWN', 'ERROR']).value_counts()}\n")
df['Quantity'] = df['Quantity'].replace(['UNKNOWN', 'ERROR'], 'unknown')
print(f"{df['Quantity'].isin(['UNKNOWN', 'ERROR']).value_counts()}\n")


print(f"{df['Price Per Unit'].isin(['UNKNOWN', 'ERROR']).value_counts()}\n")
df['Price Per Unit'] = df['Price Per Unit'].replace(['UNKNOWN', 'ERROR'], 'unknown')
print(f"{df['Price Per Unit'].isin(['UNKNOWN', 'ERROR']).value_counts()}\n")


print(f"{df['Total Spent'].isin(['UNKNOWN', 'ERROR']).value_counts()}\n")
df['Total Spent'] = df['Total Spent'].replace(['UNKNOWN', 'ERROR'], 'unknown')
print(f"{df['Total Spent'].isin(['UNKNOWN', 'ERROR']).value_counts()}\n")

Item
False    10000
Name: count, dtype: int64

Item
False    10000
Name: count, dtype: int64

Location
False    10000
Name: count, dtype: int64

Location
False    10000
Name: count, dtype: int64

Payment Method
False    10000
Name: count, dtype: int64

Payment Method
False    10000
Name: count, dtype: int64

Quantity
False    10000
Name: count, dtype: int64

Quantity
False    10000
Name: count, dtype: int64

Price Per Unit
False    9646
True      354
Name: count, dtype: int64

Price Per Unit
False    10000
Name: count, dtype: int64

Total Spent
False    9671
True      329
Name: count, dtype: int64

Total Spent
False    10000
Name: count, dtype: int64

In [ ]:
df.to_csv('cleaned_cafe_sales.csv', index=False)

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
df['Quantity'] = pd.to_numeric(df['Quantity'], errors='coerce')
df['Price Per Unit'] = pd.to_numeric(df['Price Per Unit'], errors='coerce')
df['Total Spent'] = pd.to_numeric(df['Total Spent'], errors='coerce')

In [53]:
df.loc[df['Quantity'].isna(), 'Quantity'] = df['Total Spent'] / df['Price Per Unit']
df.loc[df['Price Per Unit'].isna(), 'Price Per Unit'] = df['Total Spent'] / df['Quantity']
df.loc[df['Total Spent'].isna(), 'Total Spent'] = df['Quantity'] * df['Price Per Unit']

In [60]:
print(f"{df['Quantity'].isna().sum()}\n")

17

In [61]:
wrong = df[df['Quantity'] != df['Total Spent'] / df['Price Per Unit']]

print(wrong)

     Transaction ID      Item  Quantity  Price Per Unit  Total Spent  \
25      TXN_7958992   unknown       3.0             4.0          0.0
56      TXN_3578141  Takeaway       5.0             0.0         15.0
65      TXN_4987129  In-store       3.0             0.0          0.0
66      TXN_8501819   unknown       0.0             3.0          6.0
85      TXN_8035512   unknown       3.0             0.0          4.5
...             ...       ...       ...             ...          ...
9924    TXN_5981429   unknown       2.0             0.0          6.0
9988    TXN_9594133   unknown       5.0             3.0          0.0
9993    TXN_4766549   unknown       2.0             4.0          0.0
9996    TXN_9659401   unknown       3.0             0.0          3.0
9998    TXN_7695629   unknown       3.0             0.0          3.0

      Payment Method  Location Transaction Date
25           unknown   unknown       2023-12-13
56           unknown  Takeaway       2023-06-27
65           unknown  In-store       2023-10-20
66              Cash   unknown       2023-03-30
85              Cash   unknown       2023-10-29
...              ...       ...              ...
9924  Digital Wallet   unknown       2023-12-24
9988         unknown   unknown       1900-01-01
9993            Cash   unknown       2023-10-20
9996  Digital Wallet   unknown       2023-06-02
9998  Digital Wallet   unknown       2023-12-02

[493 rows x 8 columns]

In [67]:
mask = df[['Quantity', 'Price Per Unit', 'Total Spent']].isna().sum(axis=1) >= 2
print(mask.sum())
df = df[~mask]

0

In [70]:
print(df.info())

<class 'pandas.core.frame.DataFrame'>
Index: 9971 entries, 0 to 9999
Data columns (total 8 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Transaction ID    9971 non-null   object
 1   Item              9971 non-null   object
 2   Quantity          9971 non-null   float64
 3   Price Per Unit    9971 non-null   float64
 4   Total Spent       9971 non-null   float64
 5   Payment Method    9971 non-null   object
 6   Location          9971 non-null   object
 7   Transaction Date  9971 non-null   datetime64[ns]
dtypes: datetime64[ns](1), float64(3), object(4)
memory usage: 701.1+ KB
None

In [72]:
df.to_csv('cleaned.csv', index=False)

In [77]:
mask = df[['Quantity', 'Price Per Unit', 'Total Spent']].isna().sum(axis=1) >= 2
print(mask.sum())
df = df[~mask]

0